import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Backend Laravel Developer",
    company: "PT Sinar Mas Agro Resources and Technology Tbk",
    logo: "/images/careers/sinarmas.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2024-07",
    end_date: "2025-03",
    industry: "Agribusiness",
    link: "https://www.smart-tbk.com/",
    responsibilities: [
      "Designed and optimized robust backend services using Laravel for internal operations systems, managing large-scale data payloads across departments.",
      "Implemented secure API integrations and optimized database queries, reducing data retrieval latency by 25%.",
      "Collaborated closely with frontend developers and product owners in an Agile environment to deliver modular, maintainable, and highly secure codebase components.",
    ],
    lessons_learned: [
      "Gained hands-on experience in enterprise-level database optimization, clean architecture standards, and security auditing for internal APIs.",
      "Mastered application performance profiling and resource bottleneck identification in large-scale production environments.",
    ],
    impact: [
      "Boosted backend dashboard performance by 30% through database query refactoring and cache layer tuning.",
      "Reduced system integration errors by 15% via strict type interfaces and backend input validation schemas.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Web Developer",
    company: "Pt. Eltran Indonesia",
    logo: "/images/careers/eltran-indonesia.png",
    location: "Bandung, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Internship",
    start_date: "2025-05",
    end_date: "2025-11",
    industry: "Engineering, Procurement & Construction (EPC)",
    link: "https://eltran.co.id/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    lessons_learned: [
      "Mastered Next.js performance optimization (Core Web Vitals) and SEO best practices.",
      "Learned to bridge the gap between technical implementation and corporate branding requirements.",
    ],
    impact: [
      "Enhanced the company's digital visibility, leading to a significant increase in organic web traffic.",
      "Improved website loading speed, achieving a high Performance Score on Lighthouse.",
    ],
    isShow: false,
  },
  {
    position: "Website Developer",
    company: "CV. Griyo Electrical",
    logo: "/images/careers/griyo.jpg",
    location: "Madiun, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Contract",
    start_date: "2024-09",
    end_date: "2025-02",
    industry: "Electrical Services",
    link: "https://griyoelectrical.com",
    responsibilities: [
      "Designed, built, and deployed the official company website and service catalog from the ground up.",
      "Conducted regular security updates, performance tuning, and technical maintenance throughout the contract tenure.",
      "Optimized website layouts to ensure 100% responsiveness and user-friendly navigation for mobile visitors.",
    ],
    lessons_learned: [
      "Mastered the end-to-end development cycle for small-to-medium enterprise (SME) platforms.",
      "Enhanced project management and client communication skills by aligning technical requirements with business goals.",
    ],
    impact: [
      "Successfully established the company's official online presence, increasing potential client inquiries.",
      "Achieved 100% website uptime and lead-capture form reliability during the entire service contract.",
    ],
    isShow: true,
  },
  {
    position: "Website Developer",
    company: "PT. HwarinSkinGlow",
    logo: "/images/careers/hwarin.png",
    location: "Madiun, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Contract",
    start_date: "2025-11",
    end_date: "2026-11",
    industry: "Beauty & Personal Care",
    link: "https://hwarinskin.com",
    responsibilities: [
      "Designed and developed a secure, responsive catalog and e-commerce web platform.",
      "Implemented dynamic product list rendering, WhatsApp-direct checkout calculations, and administrative interfaces.",
      "Conducted security monitoring, API verification, and regular system backups.",
    ],
    lessons_learned: [
      "Gained deep knowledge in secure direct-checkout routing, client-side caching, and search engine metadata configuration.",
      "Mastered assets optimization and performance monitoring techniques for mobile networks.",
    ],
    impact: [
      "Boosted digital catalog loading speed by 40% through Next.js static site generation and Supabase media compression.",
      "Streamlined customer checkout routing, decreasing sales-funnel inquiry drop-offs by 15%.",
    ],
    isShow: true,
  },
  {
    position: "Maintenance Management Website",
    company: "PLN Unit Pelayanan & Jaringan (UPJ) Dolopo",
    logo: "/images/careers/pln.png",
    location: "Madiun, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Contract",
    start_date: "2023-05",
    end_date: "2023-09",
    industry: "Energy & Utilities",
    link: "https://id324023-pln-unit-pelayanan-jaringan-dolopo.contact.page/",
    responsibilities: [
      "Maintained internal operational management dashboards and database interfaces for logging UPJ statistics.",
      "Conducted system stability audits, fixed database query bottlenecks, and performed regular security patches.",
      "Provided swift technical troubleshooting support for operational dashboard issues.",
    ],
    lessons_learned: [
      "Deepened understanding of data integrity, system security standards, and high-availability operational requirements.",
      "Gained valuable experience in database performance profiling and query optimization within the utility sector.",
    ],
    impact: [
      "Maintained 100% dashboard service availability for operations teams during the entire contract tenure.",
      "Improved database log query speeds by 20% through database index refinements.",
    ],
    isShow: true,
  },
];
