import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Backend Laravel Developer",
    company: "PT Sinar Mas Agro Resources and Technology Tbk",
    logo: "/images/careers/sinarmas.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2024-07",
    end_date: "2025-03",
    industry: "Agribusiness",
    link: "https://www.smart-tbk.com/",
    responsibilities: [
      "Developed and maintained backend services using Laravel for the company's internal applications.",
      "Implemented efficient data handling and secure API integrations to support daily workflows.",
      "Collaborated with frontend and product teams to ensure smooth functionality and seamless user experience.",
    ],
    lessons_learned: [
      "Deepened understanding of Laravel's MVC pattern and Clean Architecture within a large-scale production environment.",
      "Gained hands-on experience in implementing Agile methodologies to streamline development workflows.",
      "Learned to collaborate effectively within a professional enterprise development team.",
    ],
    impact: [
      "Developed core APIs for essential functionalities, improving system reliability for internal tools.",
      "Optimized database queries for faster data retrieval and better system performance.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Web Developer",
    company: "Pt. Eltran Indonesia",
    logo: "/images/careers/eltran-indonesia.png",
    location: "Bandung, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Internship",
    start_date: "2025-05",
    end_date: "2025-11",
    industry: "Engineering, Procurement & Construction (EPC)",
    link: "https://eltran.co.id/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    lessons_learned: [
      "Mastered Next.js performance optimization (Core Web Vitals) and SEO best practices.",
      "Learned to bridge the gap between technical implementation and corporate branding requirements.",
    ],
    impact: [
      "Enhanced the company's digital visibility, leading to a significant increase in organic web traffic.",
      "Improved website loading speed, achieving a high Performance Score on Lighthouse.",
    ],
    isShow: false,
  },
  {
    position: "Website Developer",
    company: "CV. Griyo Electrical",
    logo: "/images/careers/griyo.jpg",
    location: "Madiun, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Contract",
    start_date: "2024-09",
    end_date: "2025-02",
    industry: "Electrical Services",
    link: "https://griyoelectrical.com",
    responsibilities: [
      "Designed and developed the official company website from scratch.",
      "Performed full-scale maintenance and technical support throughout the period to ensure optimal performance.",
      "Ensured the website remained responsive and user-friendly for all visitors.",
    ],
    lessons_learned: [
      "Mastered the end-to-end development cycle for a small-to-medium enterprise (SME).",
      "Improved project management and communication skills with business stakeholders.",
    ],
    impact: [
      "Successfully established the company's online presence, increasing visibility to potential clients.",
      "Ensured 100% website reliability and functionality during the contract period.",
    ],
    isShow: true,
  },
  {
    position: "Website Developer",
    company: "PT. HwarinSkinGlow",
    logo: "/images/careers/hwarin.png",
    location: "Madiun, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Contract",
    start_date: "2025-11",
    end_date: "2026-11",
    industry: "Beauty & Personal Care",
    link: "https://hwarinskin.com",
    responsibilities: [
      "Designed and developed the official e-commerce/company website.",
      "Performed full-scale maintenance and technical support throughout the period to ensure optimal performance.",
      "Implemented secure payment integrations and user-friendly product management systems.",
    ],
    lessons_learned: [
      "Mastered the integration of secure transactional systems in a production environment.",
      "Gained deep experience in long-term website maintenance and security monitoring.",
    ],
    impact: [
      "Established a robust digital sales platform, contributing to increased company revenue.",
      "Maintained 100% uptime and data integrity throughout the service period.",
    ],
    isShow: true,
  },
  {
    position: "Maintenance Management Website",
    company: "PLN Unit Pelayanan & Jaringan (UPJ) Dolopo",
    logo: "/images/careers/pln.png",
    location: "Madiun, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Contract",
    start_date: "2023-05",
    end_date: "2023-09",
    industry: "Energy & Utilities",
    link: "https://id324023-pln-unit-pelayanan-jaringan-dolopo.contact.page/",
    responsibilities: [
      "Performed full maintenance of the management website for PLN UPJ Dolopo.",
      "Ensured system stability and data accuracy within the management dashboard.",
      "Provided technical support and troubleshooting for any website-related issues.",
    ],
    lessons_learned: [
      "Gained experience in managing and maintaining industrial-level data management systems.",
      "Improved ability to ensure high system availability in a critical utility sector.",
    ],
    impact: [
      "Maintained 100% system uptime for the management dashboard during the service period.",
      "Streamlined data reporting processes through effective website maintenance.",
    ],
    isShow: true,
  },
];
