export const LOCAL_PROJECTS = [
  {
    id: 1,
    title: "EraStack — Offline-First POS",
    slug: "erastack",
    category_id: "POS & Business Platform",
    category_en: "POS & Business Platform",
    role_id: "Lead Full-Stack Developer",
    role_en: "Lead Full-Stack Developer",
    problem_id: "Aplikasi POS cloud konvensional sering gagal beroperasi saat koneksi internet toko terputus di lapangan.",
    problem_en: "Conventional cloud POS applications frequently fail during retail internet outages in field operations.",
    solution_id: "Membangun sistem kasir modern offline-first dengan SQLite lokal, dukungan printer ESC/POS thermal, dan sinkronisasi cerdas.",
    solution_en: "Engineered a modern offline-first POS platform featuring local SQLite storage, ESC/POS hardware integration, and intelligent sync.",
    result_id: "Memungkinkan transaksi toko berjalan 100% tanpa internet dengan atomic commit cepat dan keandalan tinggi.",
    result_en: "Enabled 100% offline retail operations with sub-second atomic transaction commits and high reliability.",
    description_id: "Platform POS modern untuk mengelola transaksi, produk, inventaris, laporan keuangan, dan operasional bisnis dengan arsitektur offline-first.",
    description_en: "A modern Point of Sale platform to manage transactions, products, inventory, financial analytics, and retail operations with an offline-first architecture.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "SQLite", "Offline-First", "Local AI"],
    link_demo: "https://erastack-rho.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/erastack-3.png",
      "/images/projects/erastack-1.png",
      "/images/projects/erastack-2.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 2,
    title: "Oryon Web Studio",
    slug: "oryon-web",
    category_id: "Digital Studio & Creative",
    category_en: "Digital Studio & Creative",
    role_id: "Frontend Architect",
    role_en: "Frontend Architect",
    problem_id: "Brand studio memerlukan antarmuka web modern berkinerja tinggi untuk mempresentasikan kapabilitas rekayasa digital kelas atas.",
    problem_en: "Creative studios require ultra-fast, visually stunning platforms to demonstrate high-caliber digital engineering.",
    solution_id: "Merancang website studio kreatif dengan tipografi modern, animasi micro-interaction halus, dan skor Core Web Vitals 98+.",
    solution_en: "Architected a creative digital studio platform featuring sleek typography, fluid micro-animations, and 98+ Core Web Vitals score.",
    result_id: "Meningkatkan brand trust dan inquiry klien potensial melalui pengalaman antarmuka yang sangat responsif.",
    result_en: "Elevated brand prestige and client inquiry conversions through a seamless, premium interactive interface.",
    description_id: "Platform creative digital studio yang berfokus pada pengembangan website kustom, design system modern, dan arsitektur web berperforma tinggi.",
    description_en: "A premier creative digital studio platform specializing in bespoke web development, design systems, and high-performance web architecture.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://www.oryonweb.com/",
    link_github: null,
    images: [
      "/images/projects/oryon-web-1.png",
      "/images/projects/oryon-web-2.png",
      "/images/projects/oryon-web-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 3,
    title: "Istana Gypsum",
    slug: "istana-gypsum",
    category_id: "Interior & Building Materials",
    category_en: "Interior & Building Materials",
    role_id: "Web Developer & UI Designer",
    role_en: "Web Developer & UI Designer",
    problem_id: "Katalog produk plafon dan partisi gypsum sebelumnya hanya tersedia secara offline sehingga membatasi jangkauan pasar.",
    problem_en: "Gypsum and interior partition catalogs were previously offline-only, limiting commercial market reach.",
    solution_id: "Membangun katalog digital interaktif dengan galeri material terstruktur dan simulasi estimasi proyek.",
    solution_en: "Developed an interactive digital catalog with structured material galleries and direct project inquiry channels.",
    result_id: "Memperluas jangkauan pemasaran ke skala regional dan mempercepat proses konsultasi teknis.",
    result_en: "Expanded regional commercial reach and streamlined technical client consultation workflows.",
    description_id: "Showcase digital dan katalog produk plafon gypsum, partisi ruangan, dan material konstruksi interior berkualitas tinggi.",
    description_en: "Digital showcase and product catalog for high-grade gypsum ceilings, interior partitions, and architectural construction materials.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS"],
    link_demo: "https://istana-gypsum.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/istana-gypsum-1.png",
      "/images/projects/istana-gypsum-2.png",
      "/images/projects/istana-gypsum-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 4,
    title: "Karya Tim Kontraktor",
    slug: "karyatim",
    category_id: "Construction & Architecture",
    category_en: "Construction & Architecture",
    role_id: "Full-Stack Developer",
    role_en: "Full-Stack Developer",
    problem_id: "Perusahaan kontraktor memerlukan profil portofolio yang dapat memvalidasi kredibilitas proyek bangunan skala besar.",
    problem_en: "Architectural contractors required a credible digital portfolio to showcase commercial building projects.",
    solution_id: "Mengembangkan profil korporat interaktif dengan showcase portofolio proyek selesai, timeline pekerjaan, dan form penawaran.",
    solution_en: "Created an interactive corporate profile with completed project showcases, workflow timelines, and direct quotation requests.",
    result_id: "Meningkatkan konversi tender proyek dan mempermudah presentasi hasil karya ke calon investor.",
    result_en: "Boosted client tender conversion and simplified portfolio presentations for prospective investors.",
    description_id: "Profil perusahaan dan portofolio arsitektur, jasa kontraktor bangunan, renovasi gedung, dan rekayasa struktural.",
    description_en: "Corporate profile and architectural portfolio for building contractors, commercial renovations, and structural engineering services.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://karyatim.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/karyatim-1.png",
      "/images/projects/karyatim-2.png",
      "/images/projects/karyatim-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 5,
    title: "Kalya Salon & Spa",
    slug: "kalyasalon",
    category_id: "Beauty & Wellness Booking",
    category_en: "Beauty & Wellness Booking",
    role_id: "Frontend Developer",
    role_en: "Frontend Developer",
    problem_id: "Pelanggan kesulitan melihat katalog tarif perawatan dan melakukan reservasi jadwal salon secara fleksibel.",
    problem_en: "Clients had difficulty viewing service menus and booking flexible salon appointments online.",
    solution_id: "Merancang website salon modern yang memuat katalog treatment lengkap, profil stylist, dan tombol reservasi instan.",
    solution_en: "Engineered a modern salon portal featuring comprehensive treatment menus, stylist portfolios, and instant booking actions.",
    result_id: "Meningkatkan reservasi online harian dan memberikan pengalaman reservasi yang elegan bagi pelanggan.",
    result_en: "Increased daily online booking volume and provided an elegant reservation experience for clients.",
    description_id: "Platform web salon kecantikan dan spa modern yang memuat katalog layanan perawatan rambut, kulit, dan reservasi online.",
    description_en: "A modern beauty salon and spa web platform featuring hair & skin treatment menus, stylist portfolios, and appointment booking.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS"],
    link_demo: "https://kalyasalon.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/kalyasalon-1.png",
      "/images/projects/kalyasalon-2.png",
      "/images/projects/kalyasalon-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 6,
    title: "PT Bumi Mangku Jaya",
    slug: "pt-bumimangkujaya",
    category_id: "Solid Wood & Global Furniture Export",
    category_en: "Solid Wood & Global Furniture Export",
    role_id: "Lead Web Developer",
    role_en: "Lead Web Developer",
    problem_id: "Produsen mebel kayu solid Jepara memerlukan profil B2B internasional berstandar global untuk menjangkau buyer luar negeri.",
    problem_en: "Jepara solid wood furniture manufacturers required a global B2B export portal to connect with international institutional buyers.",
    solution_id: "Merancang portal ekspor furnitur premium dengan katalog B2B terstruktur, alur kontrol kualitas manufaktur, dan formulir inquiry.",
    solution_en: "Architected a premier B2B furniture export portal featuring categorized collections, manufacturing quality workflows, and contract inquiry channels.",
    result_id: "Meningkatkan kredibilitas merek di pasar global dan mempercepat alur penawaran ekspor furnitur.",
    result_en: "Elevated brand credibility in international markets and streamlined B2B export contract inquiries.",
    description_id: "Website profil dan katalog ekspor manufaktur mebel kayu solid kelas dunia berbasis di Jepara untuk pasar B2B internasional.",
    description_en: "Official corporate export portal for world-class Jepara solid wood furniture manufacturing tailored for international B2B buyers.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "International B2B"],
    link_demo: "https://pt-bumimangkujaya.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/pt-bumimangkujaya-1.png",
      "/images/projects/pt-bumimangkujaya-2.png",
      "/images/projects/pt-bumimangkujaya-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 7,
    title: "Attic Interior Studio",
    slug: "attic-interior",
    category_id: "Interior Design & Spatial",
    category_en: "Interior Design & Spatial",
    role_id: "UI/UX & Web Developer",
    role_en: "UI/UX & Web Developer",
    problem_id: "Studio interior memerlukan galeri digital beresolusi tinggi dengan transisi visual halus untuk menampilkan detail karya estetika.",
    problem_en: "Interior design studios require high-resolution galleries with smooth visual transitions to highlight bespoke craftsmanship.",
    solution_id: "Merancang web showcase dengan gaya minimalis kontemporer, galeri interaktif, dan navigasi ruang 3D konseptual.",
    solution_en: "Designed a contemporary minimalist showcase with interactive room galleries and conceptual spatial navigation.",
    result_id: "Meningkatkan engagement pengunjung dan mengonversi pembaca menjadi klien konsultasi desain interior.",
    result_en: "Enhanced user engagement and converted prospective homeowners into interior consultation clients.",
    description_id: "Showcase portofolio desain interior residensial dan komersial, furnitur kustom, dan perencanaan ruang arsitektural modern.",
    description_en: "A contemporary design showcase for residential and commercial interiors, custom furniture, and modern spatial architecture.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://attic-interior.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/attic-interior-1.png",
      "/images/projects/attic-interior-2.png",
      "/images/projects/attic-interior-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 8,
    title: "Lombok Travel Asia",
    slug: "lomboktravelasia",
    category_id: "Travel & Tourism Booking",
    category_en: "Travel & Tourism Booking",
    role_id: "Full-Stack Developer",
    role_en: "Full-Stack Developer",
    problem_id: "Wisatawan internasional memerlukan portal wisata yang menyajikan paket perjalanan Lombok terstruktur dengan pemesanan langsung.",
    problem_en: "International travelers need a structured tourism portal presenting Lombok excursion packages with instant booking.",
    solution_id: "Membangun portal destinasi wisata dengan katalog paket tour, informasi destinasi pulau, dan booking WhatsApp otomatis.",
    solution_en: "Engineered a travel destination portal with tour package catalogs, island guides, and automated WhatsApp inquiry bookings.",
    result_id: "Mempermudah turis merencanakan liburan dan melipatgandakan reservasi paket wisata pulau.",
    result_en: "Streamlined trip planning for tourists and increased excursion package bookings.",
    description_id: "Portal pariwisata dan pemesanan paket tour pulau Lombok, snorkeling Gili, pendakian Rinjani, dan sewa transportasi wisata.",
    description_en: "A comprehensive tourism portal and tour package booking platform for Lombok island excursions, diving, and transportation.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "WhatsApp Direct"],
    link_demo: "https://lomboktravelasia.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/lomboktravelasia-1.png",
      "/images/projects/lomboktravelasia-2.png",
      "/images/projects/lomboktravelasia-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 9,
    title: "Mommy Skincare Atelier",
    slug: "mommy-skincare",
    category_id: "Beauty Atelier & AI Skin Diagnostic",
    category_en: "Beauty Atelier & AI Skin Diagnostic",
    role_id: "Full-Stack Developer",
    role_en: "Full-Stack Developer",
    problem_id: "Pelanggan sering kesulitan memilih urutan produk skincare yang cocok dengan tipe kulit spesifik dan iklim lokal.",
    problem_en: "Customers struggle to identify the correct skincare routine tailored for their unique skin profiles and tropical climate.",
    solution_id: "Mengembangkan platform beauty atelier dengan AI Routine Finder pintar, katalog produk BPOM resmi, dan order WhatsApp.",
    solution_en: "Engineered a beauty atelier platform featuring an AI Routine Diagnostic Finder, verified BPOM product catalogs, and direct WhatsApp ordering.",
    result_id: "Meningkatkan akurasi rekomendasi produk dan mempermudah pemesanan sameday delivery di 5 gerai cabang Madiun.",
    result_en: "Enhanced skincare recommendation accuracy and streamlined sameday delivery orders across 5 physical store branches.",
    description_id: "Pusat kurasi skincare & kosmetik 100% original BPOM dengan asisten AI Smart Diagnostic dan jaringan 5 store cabang Madiun.",
    description_en: "A premier beauty atelier and 100% BPOM skincare curation platform featuring an AI Diagnostic Assistant and 5 store branches.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS", "AI Diagnostics"],
    link_demo: "https://mommy-skincare.anduril.web.id",
    link_github: null,
    images: [
      "/images/projects/mommy-skincare-1.png",
      "/images/projects/mommy-skincare-2.png",
      "/images/projects/mommy-skincare-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
];
