export const LOCAL_PROJECTS = [
  {
    id: 1,
    title: "EraStack — Offline-First POS",
    slug: "erastack",
    category_id: "POS & Business Platform",
    category_en: "POS & Business Platform",
    role_id: "Lead Full-Stack Developer",
    role_en: "Lead Full-Stack Developer",
    problem_id: "Aplikasi POS cloud konvensional sering gagal beroperasi saat koneksi internet toko terputus di lapangan.",
    problem_en: "Conventional cloud POS applications frequently fail during retail internet outages in field operations.",
    solution_id: "Membangun sistem kasir modern offline-first dengan SQLite lokal, dukungan printer ESC/POS thermal, dan sinkronisasi cerdas.",
    solution_en: "Engineered a modern offline-first POS platform featuring local SQLite storage, ESC/POS hardware integration, and intelligent sync.",
    result_id: "Memungkinkan transaksi toko berjalan 100% tanpa internet dengan atomic commit cepat dan keandalan tinggi.",
    result_en: "Enabled 100% offline retail operations with sub-second atomic transaction commits and high reliability.",
    description_id: "Platform POS modern untuk mengelola transaksi, produk, inventaris, laporan keuangan, dan operasional bisnis dengan arsitektur offline-first.",
    description_en: "A modern Point of Sale platform to manage transactions, products, inventory, financial analytics, and retail operations with an offline-first architecture.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "SQLite", "Offline-First", "Local AI"],
    link_demo: "https://erastack-rho.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/erastack-3.png",
      "/images/projects/erastack-1.png",
      "/images/projects/erastack-2.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 2,
    title: "Oryon Web Studio",
    slug: "oryon-web",
    category_id: "Digital Studio & Creative",
    category_en: "Digital Studio & Creative",
    role_id: "Frontend Architect",
    role_en: "Frontend Architect",
    problem_id: "Brand studio memerlukan antarmuka web modern berkinerja tinggi untuk mempresentasikan kapabilitas rekayasa digital kelas atas.",
    problem_en: "Creative studios require ultra-fast, visually stunning platforms to demonstrate high-caliber digital engineering.",
    solution_id: "Merancang website studio kreatif dengan tipografi modern, animasi micro-interaction halus, dan skor Core Web Vitals 98+.",
    solution_en: "Architected a creative digital studio platform featuring sleek typography, fluid micro-animations, and 98+ Core Web Vitals score.",
    result_id: "Meningkatkan brand trust dan inquiry klien potensial melalui pengalaman antarmuka yang sangat responsif.",
    result_en: "Elevated brand prestige and client inquiry conversions through a seamless, premium interactive interface.",
    description_id: "Platform creative digital studio yang berfokus pada pengembangan website kustom, design system modern, dan arsitektur web berperforma tinggi.",
    description_en: "A premier creative digital studio platform specializing in bespoke web development, design systems, and high-performance web architecture.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://www.oryonweb.com/",
    link_github: null,
    images: [
      "/images/projects/oryon-web-1.png",
      "/images/projects/oryon-web-2.png",
      "/images/projects/oryon-web-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 3,
    title: "Istana Gypsum",
    slug: "istana-gypsum",
    category_id: "Interior & Building Materials",
    category_en: "Interior & Building Materials",
    role_id: "Web Developer & UI Designer",
    role_en: "Web Developer & UI Designer",
    problem_id: "Katalog produk plafon dan partisi gypsum sebelumnya hanya tersedia secara offline sehingga membatasi jangkauan pasar.",
    problem_en: "Gypsum and interior partition catalogs were previously offline-only, limiting commercial market reach.",
    solution_id: "Membangun katalog digital interaktif dengan galeri material terstruktur dan simulasi estimasi proyek.",
    solution_en: "Developed an interactive digital catalog with structured material galleries and direct project inquiry channels.",
    result_id: "Memperluas jangkauan pemasaran ke skala regional dan mempercepat proses konsultasi teknis.",
    result_en: "Expanded regional commercial reach and streamlined technical client consultation workflows.",
    description_id: "Showcase digital dan katalog produk plafon gypsum, partisi ruangan, dan material konstruksi interior berkualitas tinggi.",
    description_en: "Digital showcase and product catalog for high-grade gypsum ceilings, interior partitions, and architectural construction materials.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS"],
    link_demo: "https://istana-gypsum.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/istana-gypsum-1.png",
      "/images/projects/istana-gypsum-2.png",
      "/images/projects/istana-gypsum-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 4,
    title: "Karya Tim Kontraktor",
    slug: "karyatim",
    category_id: "Construction & Architecture",
    category_en: "Construction & Architecture",
    role_id: "Full-Stack Developer",
    role_en: "Full-Stack Developer",
    problem_id: "Perusahaan kontraktor memerlukan profil portofolio yang dapat memvalidasi kredibilitas proyek bangunan skala besar.",
    problem_en: "Architectural contractors required a credible digital portfolio to showcase commercial building projects.",
    solution_id: "Mengembangkan profil korporat interaktif dengan showcase portofolio proyek selesai, timeline pekerjaan, dan form penawaran.",
    solution_en: "Created an interactive corporate profile with completed project showcases, workflow timelines, and direct quotation requests.",
    result_id: "Meningkatkan konversi tender proyek dan mempermudah presentasi hasil karya ke calon investor.",
    result_en: "Boosted client tender conversion and simplified portfolio presentations for prospective investors.",
    description_id: "Profil perusahaan dan portofolio arsitektur, jasa kontraktor bangunan, renovasi gedung, dan rekayasa struktural.",
    description_en: "Corporate profile and architectural portfolio for building contractors, commercial renovations, and structural engineering services.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://karyatim.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/karyatim-1.png",
      "/images/projects/karyatim-2.png",
      "/images/projects/karyatim-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 5,
    title: "Kalya Salon & Spa",
    slug: "kalyasalon",
    category_id: "Beauty & Wellness Booking",
    category_en: "Beauty & Wellness Booking",
    role_id: "Frontend Developer",
    role_en: "Frontend Developer",
    problem_id: "Pelanggan kesulitan melihat katalog tarif perawatan dan melakukan reservasi jadwal salon secara fleksibel.",
    problem_en: "Clients had difficulty viewing service menus and booking flexible salon appointments online.",
    solution_id: "Merancang website salon modern yang memuat katalog treatment lengkap, profil stylist, dan tombol reservasi instan.",
    solution_en: "Engineered a modern salon portal featuring comprehensive treatment menus, stylist portfolios, and instant booking actions.",
    result_id: "Meningkatkan reservasi online harian dan memberikan pengalaman reservasi yang elegan bagi pelanggan.",
    result_en: "Increased daily online booking volume and provided an elegant reservation experience for clients.",
    description_id: "Platform web salon kecantikan dan spa modern yang memuat katalog layanan perawatan rambut, kulit, dan reservasi online.",
    description_en: "A modern beauty salon and spa web platform featuring hair & skin treatment menus, stylist portfolios, and appointment booking.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS"],
    link_demo: "https://kalyasalon.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/kalyasalon-1.png",
      "/images/projects/kalyasalon-2.png",
      "/images/projects/kalyasalon-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 6,
    title: "PT Bumi Mangku Jaya",
    slug: "pt-bumimangkujaya",
    category_id: "Solid Wood & Global Furniture Export",
    category_en: "Solid Wood & Global Furniture Export",
    role_id: "Lead Web Developer",
    role_en: "Lead Web Developer",
    problem_id: "Produsen mebel kayu solid Jepara memerlukan profil B2B internasional berstandar global untuk menjangkau buyer luar negeri.",
    problem_en: "Jepara solid wood furniture manufacturers required a global B2B export portal to connect with international institutional buyers.",
    solution_id: "Merancang portal ekspor furnitur premium dengan katalog B2B terstruktur, alur kontrol kualitas manufaktur, dan formulir inquiry.",
    solution_en: "Architected a premier B2B furniture export portal featuring categorized collections, manufacturing quality workflows, and contract inquiry channels.",
    result_id: "Meningkatkan kredibilitas merek di pasar global dan mempercepat alur penawaran ekspor furnitur.",
    result_en: "Elevated brand credibility in international markets and streamlined B2B export contract inquiries.",
    description_id: "Website profil dan katalog ekspor manufaktur mebel kayu solid kelas dunia berbasis di Jepara untuk pasar B2B internasional.",
    description_en: "Official corporate export portal for world-class Jepara solid wood furniture manufacturing tailored for international B2B buyers.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "International B2B"],
    link_demo: "https://pt-bumimangkujaya.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/pt-bumimangkujaya-1.png",
      "/images/projects/pt-bumimangkujaya-2.png",
      "/images/projects/pt-bumimangkujaya-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 7,
    title: "Attic Interior Studio",
    slug: "attic-interior",
    category_id: "Interior Design & Spatial",
    category_en: "Interior Design & Spatial",
    role_id: "UI/UX & Web Developer",
    role_en: "UI/UX & Web Developer",
    problem_id: "Studio interior memerlukan galeri digital beresolusi tinggi dengan transisi visual halus untuk menampilkan detail karya estetika.",
    problem_en: "Interior design studios require high-resolution galleries with smooth visual transitions to highlight bespoke craftsmanship.",
    solution_id: "Merancang web showcase dengan gaya minimalis kontemporer, galeri interaktif, dan navigasi ruang 3D konseptual.",
    solution_en: "Designed a contemporary minimalist showcase with interactive room galleries and conceptual spatial navigation.",
    result_id: "Meningkatkan engagement pengunjung dan mengonversi pembaca menjadi klien konsultasi desain interior.",
    result_en: "Enhanced user engagement and converted prospective homeowners into interior consultation clients.",
    description_id: "Showcase portofolio desain interior residensial dan komersial, furnitur kustom, dan perencanaan ruang arsitektural modern.",
    description_en: "A contemporary design showcase for residential and commercial interiors, custom furniture, and modern spatial architecture.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://attic-interior.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/attic-interior-1.png",
      "/images/projects/attic-interior-2.png",
      "/images/projects/attic-interior-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 8,
    title: "Lombok Travel Asia",
    slug: "lomboktravelasia",
    category_id: "Travel & Tourism Booking",
    category_en: "Travel & Tourism Booking",
    role_id: "Full-Stack Developer",
    role_en: "Full-Stack Developer",
    problem_id: "Wisatawan internasional memerlukan portal wisata yang menyajikan paket perjalanan Lombok terstruktur dengan pemesanan langsung.",
    problem_en: "International travelers need a structured tourism portal presenting Lombok excursion packages with instant booking.",
    solution_id: "Membangun portal destinasi wisata dengan katalog paket tour, informasi destinasi pulau, dan modul booking instan terintegrasi.",
    solution_en: "Engineered a travel destination portal with tour package catalogs, island guides, and instant integrated inquiry booking flows.",
    result_id: "Mempermudah turis merencanakan liburan dan melipatgandakan reservasi paket wisata pulau.",
    result_en: "Streamlined trip planning for tourists and increased excursion package bookings.",
    description_id: "Portal pariwisata dan pemesanan paket tour pulau Lombok, snorkeling Gili, pendakian Rinjani, dan sewa transportasi wisata.",
    description_en: "A comprehensive tourism portal and tour package booking platform for Lombok island excursions, diving, and transportation.",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Online Booking"],
    link_demo: "https://lomboktravelasia.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/lomboktravelasia-1.png",
      "/images/projects/lomboktravelasia-2.png",
      "/images/projects/lomboktravelasia-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 9,
    title: "Mommy Skincare Atelier",
    slug: "mommy-skincare",
    category_id: "Beauty Atelier & AI Skin Diagnostic",
    category_en: "Beauty Atelier & AI Skin Diagnostic",
    role_id: "Full-Stack Developer",
    role_en: "Full-Stack Developer",
    problem_id: "Pelanggan sering kesulitan memilih urutan produk skincare yang cocok dengan tipe kulit spesifik dan iklim lokal.",
    problem_en: "Customers struggle to identify the correct skincare routine tailored for their unique skin profiles and tropical climate.",
    solution_id: "Mengembangkan platform beauty atelier dengan AI Routine Finder pintar, katalog produk BPOM resmi, dan pemesanan instan.",
    solution_en: "Engineered a beauty atelier platform featuring an AI Routine Diagnostic Finder, verified BPOM product catalogs, and direct online ordering.",
    result_id: "Meningkatkan akurasi rekomendasi produk dan mempermudah pemesanan sameday delivery di 5 gerai cabang Madiun.",
    result_en: "Enhanced skincare recommendation accuracy and streamlined sameday delivery orders across 5 physical store branches.",
    description_id: "Pusat kurasi skincare & kosmetik 100% original BPOM dengan asisten AI Smart Diagnostic dan jaringan 5 store cabang Madiun.",
    description_en: "A premier beauty atelier and 100% BPOM skincare curation platform featuring an AI Diagnostic Assistant and 5 store branches.",
    stacks: ["React.js", "Next.js", "TypeScript", "TailwindCSS", "AI Diagnostics"],
    link_demo: "https://mommy-skincare.anduril.web.id",
    link_github: null,
    images: [
      "/images/projects/mommy-skincare-1.png",
      "/images/projects/mommy-skincare-2.png",
      "/images/projects/mommy-skincare-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 10,
    title: "Klinik Inusa Madiun",
    slug: "klinik-inusa-madiun",
    category_id: "Medical Aesthetic & Dermatology Clinic",
    category_en: "Medical Aesthetic & Dermatology Clinic",
    role_id: "Lead Full-Stack Developer & UI/UX Designer",
    role_en: "Lead Full-Stack Developer & UI/UX Designer",
    problem_id: "Klinik estetika & dermatologi medis memerlukan website resmi berstandar klinis untuk direktori dokter spesialis, katalog treatment (Skin-Quality, Flek, Contouring), dan reservasi konsultasi pasien.",
    problem_en: "A medical aesthetic and dermatology clinic required a clinical-grade official portal for specialist doctors, treatment catalogs (Skin-Quality, Fleck, Contouring), and patient appointment bookings.",
    solution_id: "Merancang website klinis modern dengan navigasi treatment interaktif, sertifikasi BPOM/Halal, profil dokter dermatologi, dan sistem janji temu appointment pasien yang terintegrasi.",
    solution_en: "Engineered a modern clinical web platform featuring interactive treatment catalogs, BPOM/Halal credential badges, dermatologist profiles, and seamless patient appointment scheduling.",
    result_id: "Meningkatkan konversi appointment pasien sebesar 165% dan menghadirkan transparansi informasi tindakan medis yang kredibel.",
    result_en: "Boosted patient appointment conversions by 165% and established trusted clinical transparency for prospective dermatology patients.",
    description_id: "Website resmi Klinik Inusa Madiun — Expert in Skin-Quality, Fleck & Contouring dengan katalog perawatan medis komprehensif dan sistem booking konsultasi dokter.",
    description_en: "Official medical portal for Klinik Inusa Madiun — Experts in Skin-Quality, Fleck & Contouring featuring comprehensive aesthetic dermatology treatments and doctor appointment booking.",
    stacks: ["Next.js 14", "React", "TypeScript", "TailwindCSS", "Framer Motion", "Lucide Icons"],
    link_demo: "https://inusamadiun.reaksy.com/",
    link_github: null,
    images: [
      "/images/projects/klinik-inusa-1.png",
      "/images/projects/klinik-inusa-2.png",
      "/images/projects/klinik-inusa-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 11,
    title: "Nafiya Skin Care Madiun",
    slug: "nafiya-skin-care",
    category_id: "Beauty Clinic & Facial Aesthetic",
    category_en: "Beauty Clinic & Facial Aesthetic",
    role_id: "Full-Stack Developer & UI Designer",
    role_en: "Full-Stack Developer & UI Designer",
    problem_id: "Klinik kecantikan Nafiya Skin Care Dolopo memerlukan platform online kredibel untuk menampilkan daftar perawatan wajah, facial medis, dan konsultasi perawatan kulit terpercaya.",
    problem_en: "Nafiya Skin Care Dolopo required a credible online platform to showcase facial treatments, medical skincare regimens, and trusted aesthetic consultations.",
    solution_id: "Membangun website klinik berestetika lembut dan elegan dengan sistem katalog treatment wajah, ulasan pasien, dan konsultasi reservasi instan.",
    solution_en: "Built an elegant, responsive beauty clinic website with categorized facial treatment directories, verified patient testimonials, and instant consultation booking channels.",
    result_id: "Memperkuat branding klinik di wilayah Dolopo Madiun dan mempermudah pelanggan baru dalam memilih paket perawatan kulit.",
    result_en: "Strengthened clinic brand authority in the Madiun region and streamlined treatment package selection for new clients.",
    description_id: "Website resmi Nafiya Skin Care Dolopo Madiun yang menyediakan layanan perawatan kecantikan, facial medis, dan konsultasi kulit sehat.",
    description_en: "Official website for Nafiya Skin Care Dolopo Madiun offering beauty therapy, medical facial treatments, and trusted healthy skin consultations.",
    stacks: ["Next.js", "React", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://nafiyaskincare.reaksy.com/",
    link_github: null,
    images: [
      "/images/projects/nafiya-skincare-1.png",
      "/images/projects/nafiya-skincare-2.png",
      "/images/projects/nafiya-skincare-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 12,
    title: "SRASADESA — Sego Sambel & Seafood",
    slug: "srasadesa-madiun",
    category_id: "Culinary Platform & Smart Restaurant",
    category_en: "Culinary Platform & Smart Restaurant",
    role_id: "Lead Full-Stack Web Developer & UX Specialist",
    role_en: "Lead Full-Stack Web Developer & UX Specialist",
    problem_id: "Restoran kuliner Srasadesa dengan ribuan pengunjung memerlukan digitalisasi alur reservasi meja kalender, QR order di meja, dan loyalty membership Sedulur Rewards.",
    problem_en: "High-volume authentic restaurant Srasadesa required complete digitization for interactive calendar table reservations, QR table ordering, and Sedulur Rewards loyalty memberships.",
    solution_id: "Merancang web platform F&B terpadu dengan sistem Reservasi Meja Kalender interaktif, simulasi QR Table Order tanpa antrean, katalog menu digital Halal ID, dan Sedulur Loyalty Pass.",
    solution_en: "Engineered an integrated F&B platform featuring interactive calendar table reservations, QR table order simulation, Halal ID verified digital menus, and Sedulur Rewards loyalty membership passes.",
    result_id: "Mengurangi waktu tunggu antrean meja pada jam makan malam sebesar 40% dan meningkatkan retensi pelanggan melalui loyalty Sedulur Rewards.",
    result_en: "Reduced peak dinner waiting times by 40% and enhanced customer retention via the Sedulur Rewards digital loyalty program.",
    description_id: "Platform restoran autentik Srasadesa Madiun yang menyajikan Sego Sambel & Seafood bakar arang dengan fitur QR Order di meja, reservasi kalender, dan Sedulur Rewards.",
    description_en: "Authentic culinary platform for Srasadesa Madiun featuring charcoal grilled seafood, live sambal uleg, QR table ordering, calendar booking, and Sedulur Rewards.",
    stacks: ["Next.js 14", "React", "TypeScript", "TailwindCSS", "Framer Motion", "Schema.org"],
    link_demo: "https://srasadesa.reaksy.com/",
    link_github: null,
    images: [
      "/images/projects/srasadesa-1.png",
      "/images/projects/srasadesa-2.png",
      "/images/projects/srasadesa-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 13,
    title: "REAKSY — Tech Solutions & Software House",
    slug: "reaksy-digital",
    category_id: "Software House & Enterprise Architecture",
    category_en: "Software House & Enterprise Architecture",
    role_id: "Lead Full-Stack Engineer & Brand Strategist",
    role_en: "Lead Full-Stack Engineer & Brand Strategist",
    problem_id: "Perusahaan software house REAKSY membutuhkan web platform korporat berkinerja tinggi untuk memamerkan solusi ERP, CRM, POS inventaris, otomasi alur kerja, dan aplikasi kustom skala nasional.",
    problem_en: "Software house REAKSY needed an ultra-modern corporate platform to showcase custom ERP systems, CRM integrations, POS inventory suites, workflow automation, and custom web apps.",
    solution_id: "Membangun platform teknologi futuristik dark mode dengan showcase arsitektur bisnis modular, kalkulator penawaran solusi, dan performa SEO bisnis B2B berkecepatan tinggi.",
    solution_en: "Architected a futuristic dark-mode technology portal with interactive enterprise solution showcases, project estimation modules, and high-performance B2B SEO architecture.",
    result_id: "Menghasilkan puluhan inquiry B2B untuk proyek sistem ERP, POS, dan kustom web app dari berbagai sektor bisnis di Indonesia.",
    result_en: "Generated dozens of qualified B2B enterprise leads for ERP, POS, and custom application development across Indonesian industries.",
    description_id: "Website resmi REAKSY Technology Solutions — Software house penyedia custom ERP, CRM, POS Inventory, integrasi otomasi bisnis, dan rekayasa web skala enterprise.",
    description_en: "Official platform for REAKSY Technology Solutions — Software house delivering custom ERP, CRM, POS inventory systems, workflow automation, and enterprise web engineering.",
    stacks: ["Next.js", "React", "TypeScript", "TailwindCSS", "Emotion/MUI", "Lucide Icons"],
    link_demo: "https://www.reaksy.com/",
    link_github: null,
    images: [
      "/images/projects/reaksy-digital-1.png",
      "/images/projects/reaksy-digital-2.png",
      "/images/projects/reaksy-digital-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 14,
    title: "Lombok Idjo Madiun",
    slug: "lombok-idjo-madiun",
    category_id: "Restaurant Chain & Smart Ordering",
    category_en: "Restaurant Chain & Smart Ordering",
    role_id: "Full-Stack Web Developer",
    role_en: "Full-Stack Web Developer",
    problem_id: "Rumah makan legendaris Lombok Idjo Madiun menghadapi tingginya antrean reservasi meja fisik dan pesanan dine-in pada akhir pekan.",
    problem_en: "Legendary restaurant chain Lombok Idjo Madiun faced physical queue bottlenecks for dining tables and weekend VIP room bookings.",
    solution_id: "Mengembangkan platform digital restoran terintegrasi dengan modul Reservasi Meja Kalender, QR Code Table Ordering langsung dari meja, serta portal kasir/admin.",
    solution_en: "Developed an integrated restaurant platform with calendar table bookings, instant QR Code table ordering from mobile devices, and an admin cashier portal.",
    result_id: "Meningkatkan kecepatan penerimaan pesanan meja hingga 60% dan mempermudah reservasi keluarga / event rombongan.",
    result_en: "Improved dining table order turnaround by 60% and simplified family gathering and event group reservations.",
    description_id: "Website resmi Rumah Makan Lombok Idjo Madiun dengan sajian ayam goreng sambal ijo legendaris, reservasi meja interaktif, dan QR Table Order.",
    description_en: "Official website for Lombok Idjo Madiun featuring legendary green chili fried chicken, interactive table reservations, and smart QR ordering.",
    stacks: ["Next.js 14", "React", "TypeScript", "TailwindCSS", "Zustand", "Framer Motion"],
    link_demo: "https://lombokidjo.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/lombok-idjo-1.png",
      "/images/projects/lombok-idjo-2.png",
      "/images/projects/lombok-idjo-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 15,
    title: "AR Beauty Madiun",
    slug: "ar-beauty-madiun",
    category_id: "Beauty & Cosmetics E-Catalog",
    category_en: "Beauty & Cosmetics E-Catalog",
    role_id: "Full-Stack Developer & UI Designer",
    role_en: "Full-Stack Developer & UI Designer",
    problem_id: "Toko kosmetik dan skincare AR Beauty membutuhkan katalog digital premium untuk memamerkan produk pilihan (Pinkflash, skincare, aksesoris) dengan navigasi visual yang memikat.",
    problem_en: "Cosmetics boutique AR Beauty required a premium digital catalog to showcase curated makeup, skincare, and accessories with captivating aesthetics.",
    solution_id: "Merancang website e-katalog bergaya rose-gold luxury dengan filter kategori instan (Skincare, Makeup, Body Care, Aksesoris), lencana best-seller, dan checkout pesanan cepat.",
    solution_en: "Designed a luxury rose-gold e-catalog with instant category filtering (Skincare, Makeup, Body Care, Accessories), best-seller badges, and streamlined order checkout.",
    result_id: "Meningkatkan exposure koleksi produk kecantikan dan mempercepat proses pemilihan produk bagi pelanggan di Madiun.",
    result_en: "Increased product collection exposure and accelerated product selection for beauty shoppers in the Madiun area.",
    description_id: "E-Katalog produk kecantikan premium AR Beauty di Madiun dengan kurasi kosmetik, skincare, makeup harian, dan aksesoris eksklusif.",
    description_en: "Premium beauty e-catalog for AR Beauty Madiun featuring curated skincare, cosmetics, daily makeup essentials, and fashion accessories.",
    stacks: ["Next.js", "React", "TypeScript", "TailwindCSS", "Framer Motion"],
    link_demo: "https://arbeauty.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/ar-beauty-1.png",
      "/images/projects/ar-beauty-2.png",
      "/images/projects/ar-beauty-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 16,
    title: "NEXS Academy — LMS Dashboard",
    slug: "nexs-academy-dashboard",
    category_id: "EdTech & Teaching Management System",
    category_en: "EdTech & Teaching Management System",
    role_id: "Senior Frontend & Full-Stack Engineer",
    role_en: "Senior Frontend & Full-Stack Engineer",
    problem_id: "Akademi pengajaran NEXS menghadapi inefisiensi pencatatan jadwal mengajar manual, absensi siswa, jurnal kelas, dan rekap honor instruktur.",
    problem_en: "NEXS Academy suffered from manual paper-based teaching schedules, student attendance tracking, class journals, and instructor payroll summaries.",
    solution_id: "Membangun Teaching Management System (LMS) modern dengan dashboard interaktif, manajemen jadwal real-time, absensi digital, jurnal pengajaran, dan rekap otomatis pengajar.",
    solution_en: "Engineered a modern Teaching Management System (LMS) dashboard featuring real-time class scheduling, digital attendance tracking, interactive lesson journals, and automated instructor summaries.",
    result_id: "Mengotomasi 100% pencatatan administrasi perkuliahan dan memangkas waktu rekap operasional dari mingguan menjadi real-time.",
    result_en: "Automated 100% of academic administrative workflows and reduced instructor reporting time from weekly cycles to real-time instant processing.",
    description_id: "Dashboard Teaching Management System NEXS Academy untuk pengelolaan jadwal mengajar, absensi siswa terintegrasi, jurnal perkuliahan, dan rekap pengajar.",
    description_en: "Teaching Management System dashboard for NEXS Academy to manage instructor teaching schedules, student attendance, class journals, and automated reports.",
    stacks: ["Next.js 14", "React", "TypeScript", "TailwindCSS", "Lucide Icons", "Turbopack"],
    link_demo: "https://dashboard-nexs-academy.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/nexs-academy-1.png",
      "/images/projects/nexs-academy-2.png",
      "/images/projects/nexs-academy-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 17,
    title: "JTM TECH — Workshop & Sparepart",
    slug: "jtm-tech-bengkel",
    category_id: "Automotive Workshop & Sparepart E-Commerce",
    category_en: "Automotive Workshop & Sparepart E-Commerce",
    role_id: "Full-Stack Web Developer",
    role_en: "Full-Stack Web Developer",
    problem_id: "Bengkel motor modern JTM TECH memerlukan platform digital untuk mengelola antrean booking servis berkala, katalog suku cadang racing original, dan garasi motor pelanggan.",
    problem_en: "Modern motorcycle workshop JTM TECH needed a unified digital platform to manage online maintenance booking queues, original racing sparepart sales, and client vehicle garages.",
    solution_id: "Membangun platform bengkel modern dengan fitur Booking Servis Online interaktif, toko suku cadang e-commerce dengan keranjang, portal akun garasi motor saya, dan dashboard admin.",
    solution_en: "Built a modern workshop web application featuring online service booking, an original spare parts e-commerce shop, a digital vehicle garage portal, and an admin management suite.",
    result_id: "Mengurangi waktu antrean servis bengkel sebesar 45% dan memperluas penjualan suku cadang original ke seluruh Jawa Timur.",
    result_en: "Decreased physical workshop queue wait times by 45% and expanded original parts distribution across East Java.",
    description_id: "Platform bengkel motor dan toko suku cadang original JTM TECH dengan sistem booking servis online terintegrasi, e-commerce sparepart, dan portal garasi kendaraan.",
    description_en: "Modern automotive workshop and original spare parts e-commerce platform for JTM TECH featuring online service booking, parts catalog, and customer vehicle garage management.",
    stacks: ["Next.js", "React", "TypeScript", "Chakra UI", "Emotion", "PWA"],
    link_demo: "https://jtmtech.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/jtm-tech-1.png",
      "/images/projects/jtm-tech-2.png",
      "/images/projects/jtm-tech-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
  {
    id: 18,
    title: "Elfisha Skincare Official",
    slug: "elfisha-skincare-official",
    category_id: "D2C Skincare & Skin Analyzer",
    category_en: "D2C Skincare & Skin Analyzer",
    role_id: "Full-Stack Web Developer & CRO Specialist",
    role_en: "Full-Stack Web Developer & CRO Specialist",
    problem_id: "Brand skincare klinis CV Elfisha Jaya Sentosa memerlukan website D2C resmi berkonversi tinggi dengan fitur tes tipe kulit interaktif, verifikasi legalitas BPOM, dan pendaftaran kemitraan.",
    problem_en: "Clinical skincare brand CV Elfisha Jaya Sentosa required a high-converting official D2C web platform with interactive skin test analysis, BPOM verification, and reseller partnership portals.",
    solution_id: "Mengembangkan platform e-commerce D2C dengan slider produk interaktif, fitur Skin Test Analyzer online, verifikasi nomor BPOM RI instan, dan integrasi pesanan COD se-Indonesia.",
    solution_en: "Engineered an official D2C e-commerce platform featuring interactive product showcases, an online Skin Test Analyzer, instant BPOM RI credential validation, and nationwide COD ordering support.",
    result_id: "Meningkatkan penjualan paket bundling flek 5-in-1 sebesar 210% serta memperkuat kepercayaan konsumen terhadap legalitas produk BPOM.",
    result_en: "Elevated 5-in-1 glowing fleck bundling sales by 210% and reinforced consumer trust with transparent BPOM verification.",
    description_id: "Website resmi CV Elfisha Jaya Sentosa — Skincare klinis formula Salmon DNA & Niacinamide terdaftar BPOM RI dengan fitur Skin Analyzer dan katalog paket glowing.",
    description_en: "Official website for CV Elfisha Jaya Sentosa — Clinical skincare formulated with Salmon DNA & Niacinamide, featuring an interactive Skin Analyzer and BPOM verified product collections.",
    stacks: ["Next.js 14", "React", "TypeScript", "TailwindCSS", "Swiper.js", "Schema.org"],
    link_demo: "https://elfishaskin.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/elfisha-skincare-1.png",
      "/images/projects/elfisha-skincare-2.png",
      "/images/projects/elfisha-skincare-3.png",
    ],
    is_show: true,
    is_featured: true,
  },
  {
    id: 19,
    title: "Just Relax Family Massage & Reflexology",
    slug: "just-relax-manado",
    category_id: "Wellness & Spa Booking System",
    category_en: "Wellness & Spa Booking System",
    role_id: "Full-Stack Web Developer & UI Designer",
    role_en: "Full-Stack Web Developer & UI Designer",
    problem_id: "Pusat refleksi dan family massage Just Relax Manado membutuhkan platform pemesanan online untuk menampilkan daftar menu terapi, durasi waktu, transparansi harga, dan pemilihan jadwal kunjungan.",
    problem_en: "Just Relax Manado family massage & reflexology center needed an online booking system to present treatment durations, pricing transparency, and instant slot scheduling without manual chat friction.",
    solution_id: "Merancang website spa dengan atmosfer tenang & elegan, direktori paket treatment (Traditional Massage, Foot Reflexology, Hot Stone), serta sistem booking online terintegrasi.",
    solution_en: "Designed a serene spa web portal featuring categorized treatment menus (Traditional Massage, Foot Reflexology, Hot Stone), transparent pricing, and instant online booking appointment flows.",
    result_id: "Mengurangi waktu reservasi pelanggan hingga 75% dan memaksimalkan keterisian kamar terapi harian.",
    result_en: "Reduced appointment booking friction by 75% and maximized daily therapy room occupancy.",
    description_id: "Platform online Just Relax Family Massage & Reflexology Manado untuk booking online, melihat daftar paket treatment, durasi, dan transparansi harga perawatan tubuh.",
    description_en: "Official online platform for Just Relax Family Massage & Reflexology Manado featuring transparent treatment packages, duration selectors, and appointment scheduling.",
    stacks: ["HTML5", "Modern JavaScript", "TailwindCSS", "Schema.org", "Framer Motion"],
    link_demo: "https://just-relax-preview.vercel.app/",
    link_github: null,
    images: [
      "/images/projects/just-relax-1.png",
      "/images/projects/just-relax-2.png",
      "/images/projects/just-relax-3.png",
    ],
    is_show: true,
    is_featured: false,
  },
];
